ConcatenatedPrimes: src/concat_primes.cpp File Reference
concat_primes.cpp File Reference
Prints segments of prime numbers based on user input.
#include <iostream>
#include <string>
#include <cmath>
#include <assert.h>
Functions
std::string get_concatenated_primes ()
std::string get_slice_of_5 (const std::string &primes, const int index)
int main (int argc, char *argv[])
Detailed Description
Prints segments of prime numbers based on user input.
This program creates and concatenates a string of prime numbers such that the string is 1000 numbers long. After that the program accepts user input in the form of an integer between 1 and 1000 and subsequently prints to the screen the 5 character long segment of corresponding digits.
Requires: C++11
Function Documentation
std::string get_concatenated_primes ()
This function generates a 1003 character list of prime numbers
This function loops through numbers and analyzes if they are prime or not. It then takes all the numbers deemed as primes and adds them to the string of primes. The loop runs until there are 1000 characters in the string
Returns
std::string
Referenced by main().
std::string get_slice_of_5 (const std::string & primes, const int index)
this function is used to get a slice of 5 digits from the concatenated prime string
Referenced by main().
int main (int argc, char * argv[])
References get_concatenated_primes(), and get_slice_of_5().